### ISSUE TITLE
Minimal Build Image

### ISSUE THREAD

**Issue by thekief** [maistra/test-infra#354]
Starting with the unification of the build Dockerfiles quite a lot of additional applications have been added. 

I was wondering which dependencies could be, e.g., removed in `docker/maistra-builder_2.3.Dockerfile` without affecting a simple build. I am pretty sure that I won't need things such as **kubectl**, the GitHub CLI and so on but I am not sure about things such as `yq`. Could you point me in the proper direction?

**Comment by jwendell** [comment]
Why are you pretty sure we don't need such tools?
Those images are used to run unit & integration tests in istio and operator repositories.

They are inspired by istio images: https://github.com/istio/tools/blob/master/docker/build-tools/Dockerfile

**Comment by thekief** [comment]
That's why I wrote "I am pretty sure that I won't need things such as kubectl" :sweat_smile: 

I would like to build the proxy without testing it, as I make some adaptions but can only test the using integrative tests anyway. Thus, I was wondering if and which dependencies can be removed without affecting the setup's ability to build the proxy.

**Comment by jwendell** [comment]
Not sure if you are planning to submit your changes to our repo or if it's just something you will do in your side. You can experiment removing all dependencies you think are not needed, and try to build proxy. If it fails due to lack of any dependency, you can add it back. As a start point, I know that clang and bazel are required to build it, so, I'd not remove them.

**Comment by thekief** [comment]
I will not submit the changes as you mentioned that everything is needed as is. I was tasked to slim down the build image and was wondering about quite a lot of dependencies, as I wasn't sure if they are need for WASM or other similar things.

I will start with **clang** and **bazel** then.
